#!/usr/bin/env bash

# This is a little script that:
# 1. syncs the upstream master with origin master
# 2. and then rebases the current branch to upstream master using the merge strategy
#
# Usage:
# git-rebase


if [ -n "$(git status -s -uno)" ]; then
    echo "Error: you have uncommitted git files; either git stash or git commit them first"
    exit 1
fi

cur_branch=$(git branch | sed -n '/\* /s///p')
if [ "$cur_branch" = "master" ]; then
    echo "Error: this script expects you to be on the branch you need to rebase, but this is a 'master' branch"
    echo "Exiting"
    exit 1
fi

# my script github-make-pr-branch sets up upstream git remote, when creating a branch, so here we
# know if we are in a branch of a forked repo and need to merge the forked master first. I'm not
# sure how to do this check in a general way w/o having an explicit `upstream` set up
if [ -n "$(git remote get-url upstream 2> /dev/null)" ]; then
    echo "detected a fork, merging upstream/master into origin/master first"
    git fetch upstream
    git checkout master
    git merge --no-edit upstream/master
    git push --set-upstream origin master
    git checkout -
else
    echo "detected non-forked repo, updating origin"
    git fetch origin
fi

git pull --rebase
git merge origin/master

echo "Now resolve conflicts if any, followed by git commit and finally git push"
